image: "rust:latest"

stages:
  - build
  - test

compile:
  stage: build
  script:
    cargo build -r
  artifacts:
    paths:
      - target/release
  tags:
    - shared-fi

cargo_test:
  stage: test
  script:
    - cargo test --workspace --verbose
  dependencies:
    - compile
  tags:
    - shared-fi
